require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.0.0'

platform :ios, '10.0'

target 'initialproject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'KakaoOpenSDK', '~> 1.21.0'
  # pod 'GoogleSignIn'
  # pod 'Firebase'
  # pod 'KakaoOpenSDK'


  # target 'initialprojectTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

# target 'initialproject-tvOS' do
#   # Pods for initialproject-tvOS

#   target 'initialproject-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
