version: "3.7"

services:
  app.example.io:
    build: .
    restart: on-failure
    volumes:
      - ./docs:/usr/src/app/docs
      - ./pages:/usr/src/app/pages
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./scripts:/usr/src/app/scripts
      - ./public:/usr/src/app/public
      - ./uploads:/usr/src/app/uploads
      - ./config:/usr/src/app/config
    command: "/bin/sh -c 'yarn dev'"
    ports:
      - 8080:8080
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres.example.io
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: EXf3hZXz4Kzqx5sr
      DB_DATABASE: example
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  postgres.example.io:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: EXf3hZXz4Kzqx5sr
      POSTGRES_DB: example
    volumes:
      - volume.postgres.example.io:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432" # temporary
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  volume.postgres.example.io:

networks:
  default:
    # external: true
    name: example.io
